import { Language } from '@/types';

export interface DemoScenario {
  id: string;
  title: string;
  language: Language;
  userPrompt: string;
  expectedServiceId: string;
  description: string;
}

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'scenario-a-marathi-income',
    title: 'Scenario A: Income Certificate (मराठी)',
    language: 'mr',
    userPrompt: 'मला उत्पन्न प्रमाणपत्र काढायचं आहे.',
    expectedServiceId: 'income-certificate',
    description: 'Demonstrates Marathi natural language detection, intent extraction, income certificate matching, and guided task journey.',
  },
  {
    id: 'scenario-b-residence-english',
    title: 'Scenario B: Residence Proof (English)',
    language: 'en',
    userPrompt: 'I need a document that proves where I live.',
    expectedServiceId: 'residence-certificate',
    description: 'Demonstrates intent-first matching when the citizen does not know the official administrative term "Domicile Certificate".',
  },
  {
    id: 'scenario-c-upi-marathi',
    title: 'Scenario C: Digital Payments / UPI (मराठी)',
    language: 'mr',
    userPrompt: 'मला UPI वापरायला शिकायचं आहे.',
    expectedServiceId: 'digital-payments-safety',
    description: 'Directs citizen to safe digital payments learning, emphasizing PIN safety and fraud prevention.',
  },
  {
    id: 'scenario-d-scholarship-hindi',
    title: 'Scenario D: College Scholarship (हिंदी)',
    language: 'hi',
    userPrompt: 'मुझे कॉलेज फीस और छात्रवृत्ति के लिए सरकारी मदद चाहिए।',
    expectedServiceId: 'post-matric-scholarship',
    description: 'Identifies education welfare and post-matric scholarship with Aadhaar bank seeding verification steps.',
  },
];

export interface SampleScreenItem {
  id: string;
  title: string;
  category: string;
  imageUrl: string;
  sampleDescription: string;
  simulatedExplanation: {
    screenTitle: string;
    summary: string;
    requiredFields: { fieldName: string; description: string; expectedInput: string }[];
    terminologyDefinitions: { term: string; plainExplanation: string }[];
    nextAction: string;
    cautionPoints: string[];
    disclaimer: string;
  };
}

export const SAMPLE_SCREENS: SampleScreenItem[] = [
  {
    id: 'screen-document-upload',
    title: 'Portal Document Upload & Format Restriction Screen',
    category: 'Government Certificate Portal',
    imageUrl: '/images/sample-screen-upload.svg',
    sampleDescription: 'Confusing upload form asking for "Self-Declaration Form 1", specific DPI, and max 100KB file sizes.',
    simulatedExplanation: {
      screenTitle: 'Supporting Document Attachment Page (Aaple Sarkar / e-District)',
      summary: 'This page requires you to attach digital copies of your Identity Proof, Address Proof, and Income Declaration before submitting your application.',
      requiredFields: [
        {
          fieldName: 'Proof of Identity (PoI)',
          description: 'Document verifying who you are.',
          expectedInput: 'Choose file: Aadhaar Card or Voter ID in PDF format under 256 KB.',
        },
        {
          fieldName: 'Self-Declaration Affidavit',
          description: 'A signed statement confirming your reported income is truthful.',
          expectedInput: 'Download the given template, sign with blue/black pen, take a clear photo, and upload.',
        },
        {
          fieldName: 'Photograph (Resolution: 160x212 px)',
          description: 'Passport size photo of applicant.',
          expectedInput: 'A clear front-facing image (JPG format, file size between 20 KB and 50 KB).',
        },
      ],
      terminologyDefinitions: [
        {
          term: 'PoI / PoA',
          plainExplanation: 'Proof of Identity (PoI) proves your name. Proof of Address (PoA) proves your residence.',
        },
        {
          term: 'Self-Declaration',
          plainExplanation: 'A standard simple form where you officially declare that the details provided are true under penalty of law.',
        },
        {
          term: 'File size limit (KB)',
          plainExplanation: 'The portal limits upload size so its servers do not slow down. If your file is too big, use a free photo compressor.',
        },
      ],
      nextAction: 'Take clear photos of your Aadhaar card and electricity bill, verify the text is readable, and click "Choose File" for each corresponding row.',
      cautionPoints: [
        'Do not upload blurred or cut-off photographs.',
        'Ensure the name on your identity proof exactly matches the name entered in the application form.',
      ],
      disclaimer: 'This explanation is generated by Sahayak AI to assist you with terminology. Always verify required parameters on the official government portal.',
    },
  },
  {
    id: 'screen-fee-payment',
    title: 'Statutory Fee Checkout & Treasury Challan Screen',
    category: 'Online Payment Gateway',
    imageUrl: '/images/sample-screen-payment.svg',
    sampleDescription: 'Complex payment screen with GRAS / Treasury challan terms, convenience fee tables, and gateway selections.',
    simulatedExplanation: {
      screenTitle: 'Government Revenue Account System (GRAS) Payment Gateway',
      summary: 'This screen is asking you to pay the mandatory government processing fee (₹33.60) to complete your application submission.',
      requiredFields: [
        {
          fieldName: 'Payment Mode',
          description: 'Method to pay the processing fee.',
          expectedInput: 'Select "UPI / QR Code" for the fastest and safest zero-surcharge experience.',
        },
        {
          fieldName: 'Captcha Code',
          description: 'Security letters shown on screen.',
          expectedInput: 'Type the exact letters and numbers displayed in the grey image box.',
        },
      ],
      terminologyDefinitions: [
        {
          term: 'GRAS / Treasury Challan',
          plainExplanation: 'The official receipt system that deposits your fee directly into the state government revenue account.',
        },
        {
          term: 'Convenience Fee',
          plainExplanation: 'A small processing fee charged by banks (typically ₹0 for UPI, or ₹2 to ₹5 for net banking).',
        },
      ],
      nextAction: 'Click on "UPI / QR Code", scan the QR code using your authorized banking or UPI app, verify the fee amount (approx ₹33), and confirm payment.',
      cautionPoints: [
        'Never refresh or press the browser "Back" button while the payment is processing.',
        'Remember: you will enter your UPI PIN on your phone to PAY, never to receive.',
      ],
      disclaimer: 'Sahayak AI does not process payments. Always verify the secure lock icon in your browser address bar on the payment page.',
    },
  },
];
